/*
// * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
// * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
// */
//package GUI;
//
//import java.awt.Color;
//import java.awt.Cursor;
//import java.awt.Dimension;
//import java.awt.Font;
//import java.awt.Panel;
//import java.sql.Date;
//import java.time.LocalDate;
//
//import javax.swing.Icon;
//import javax.swing.ImageIcon;
//import javax.swing.JPanel;
//
//import com.toedter.calendar.JDateChooser;
//
///**
// *
// * @author Asus
// */
//public class FRMQuanLiThongKe extends javax.swing.JFrame {
//
//	/**
//	 * Creates new form FRMQuanLiThongKe
//	 */
//	public FRMQuanLiThongKe() {
//		initComponents();
//	}
//
//	public JPanel getFRMThongKe() {
//		return jPanel1;
//	}
//
//	/**
//	 * This method is called from within the constructor to initialize the form.
//	 * WARNING: Do NOT modify this code. The content of this method is always
//	 * regenerated by the Form Editor.
//	 */
//	@SuppressWarnings("unchecked")
//	// <editor-fold defaultstate="collapsed" desc="Generated
//	// Code">//GEN-BEGIN:initComponents
//	private void initComponents() {
//
//		jPanel1 = new javax.swing.JPanel();
//		jLabel1 = new javax.swing.JLabel();
//		jbThongKe = new javax.swing.JButton();
//		jbLamMoiTK = new javax.swing.JButton();
//		jScrollPane1 = new javax.swing.JScrollPane();
//		jTextArea1 = new javax.swing.JTextArea();
//		jScrollPane2 = new javax.swing.JScrollPane();
//		jTextArea2 = new javax.swing.JTextArea();
//		jLabel2 = new javax.swing.JLabel();
//		jScrollPane3 = new javax.swing.JScrollPane();
//		jTextArea3 = new javax.swing.JTextArea();
//
//
//		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//		setPreferredSize(new java.awt.Dimension(1202, 422));
//
//		jPanel1.setPreferredSize(new java.awt.Dimension(1202, 422));
//
//		jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
//		jLabel1.setText("Đến ngày:");
//
//		jbThongKe.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
//		jbThongKe.setIcon(new javax.swing.ImageIcon("D:\\PhatTrienUngDung\\baiTapLonCKPTUD\\baiTapLonCKPTUD\\iCon\\analytics.png")); // NOI18N
//		jbThongKe.setText("Thống kê");
//
//		jbLamMoiTK.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
//		jbLamMoiTK.setIcon(new javax.swing.ImageIcon("D:\\PhatTrienUngDung\\baiTapLonCKPTUD\\baiTapLonCKPTUD\\iCon\\refresh.png")); // NOI18N
//		jbLamMoiTK.setText("Làm mới");
//
//		jTextArea1.setColumns(20);
//		jTextArea1.setRows(5);
//		jScrollPane1.setViewportView(jTextArea1);
//
//		jTextArea2.setColumns(20);
//		jTextArea2.setRows(5);
//		jScrollPane2.setViewportView(jTextArea2);
//
//		now = LocalDate.now();
//		ngay = now.getDayOfMonth();
//		thang = now.getMonthValue()-1;
//		nam = now.getYear()-1900;
//
//		dNow = new Date(nam,thang,ngay);
//
//		dateChooserThongKeNgayBatDau = new JDateChooser();
//		dateChooserThongKeNgayBatDau.setDateFormatString("dd/MM/yyyy");
//
//		dateChooserThongKeNgayBatDau.setFont(new Font("SansSerif", Font.PLAIN, 15));
//		dateChooserThongKeNgayBatDau.getCalendarButton().setPreferredSize(new Dimension(30, 24));
//		dateChooserThongKeNgayBatDau.getCalendarButton().setBackground(new Color(102, 0, 153));
//
//		dateChooserThongKeNgayBatDau.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
//		dateChooserThongKeNgayBatDau.setBounds(130, 15, 180, 38);
//		dateChooserThongKeNgayBatDau.setDate(dNow);
//
//
//
//		dateChooserThongKeNgayKetThuc = new JDateChooser();
//		dateChooserThongKeNgayKetThuc.getCalendarButton().setPreferredSize(new Dimension(30, 24));
//
//		dateChooserThongKeNgayKetThuc.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
//		dateChooserThongKeNgayKetThuc.getCalendarButton().setBackground(new Color(102, 0, 153));
//		dateChooserThongKeNgayKetThuc.setFont(new Font("SansSerif", Font.PLAIN, 15));
//		dateChooserThongKeNgayKetThuc.setDateFormatString("dd/MM/yyyy");
//		dateChooserThongKeNgayKetThuc.setBounds(130, 60, 180, 38);
//		dateChooserThongKeNgayKetThuc.setDate(dNow);
//
//
//		jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
//		jLabel2.setText("Từ ngày:");
//
//		jTextArea3.setColumns(20);
//		jTextArea3.setRows(5);
//		jScrollPane3.setViewportView(jTextArea3);
//
//		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//		jPanel1.setLayout(jPanel1Layout);
//		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//								.addComponent(jScrollPane3)
//								.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
//										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//										.addGroup(jPanel1Layout.createSequentialGroup().addGap(21, 21, 21)
//												.addGroup(jPanel1Layout
//														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//														.addGroup(jPanel1Layout.createSequentialGroup()
//																.addComponent(jLabel2)
//																.addPreferredGap(
//																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
//																		javax.swing.GroupLayout.DEFAULT_SIZE,
//																		Short.MAX_VALUE)
//																.addComponent(dateChooserThongKeNgayBatDau,
//																		javax.swing.GroupLayout.PREFERRED_SIZE, 159,
//																		javax.swing.GroupLayout.PREFERRED_SIZE))
//														.addGroup(jPanel1Layout.createSequentialGroup()
//																.addComponent(jLabel1)
//																.addPreferredGap(
//																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
//																		61, Short.MAX_VALUE)
//																.addComponent(dateChooserThongKeNgayKetThuc,
//																		javax.swing.GroupLayout.PREFERRED_SIZE, 159,
//																		javax.swing.GroupLayout.PREFERRED_SIZE))))
//										.addGroup(jPanel1Layout.createSequentialGroup().addGap(12, 12, 12)
//												.addGroup(jPanel1Layout
//														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//														.addComponent(jbThongKe,
//																javax.swing.GroupLayout.Alignment.TRAILING,
//																javax.swing.GroupLayout.DEFAULT_SIZE,
//																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//														.addComponent(jbLamMoiTK, javax.swing.GroupLayout.DEFAULT_SIZE,
//																javax.swing.GroupLayout.DEFAULT_SIZE,
//																Short.MAX_VALUE))))
//										.addGap(18, 18, 18)
//										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431,
//												javax.swing.GroupLayout.PREFERRED_SIZE)
//										.addGap(18, 18, 18).addComponent(jScrollPane2,
//												javax.swing.GroupLayout.PREFERRED_SIZE, 431,
//												javax.swing.GroupLayout.PREFERRED_SIZE)))
//						.addGap(18, 18, 18)));
//		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
//						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//						.addGroup(jPanel1Layout.createSequentialGroup()
//								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//										.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
//												javax.swing.GroupLayout.PREFERRED_SIZE)
//										.addComponent(dateChooserThongKeNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
//												javax.swing.GroupLayout.PREFERRED_SIZE))
//								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//										.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
//												javax.swing.GroupLayout.PREFERRED_SIZE)
//										.addComponent(dateChooserThongKeNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
//												javax.swing.GroupLayout.PREFERRED_SIZE))
//								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
//										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//								.addComponent(jbThongKe)
//								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//								.addComponent(jbLamMoiTK))
//						.addComponent(jScrollPane1).addComponent(jScrollPane2))
//						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//						.addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
//						.addContainerGap()));
//
//		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//		getContentPane().setLayout(layout);
//		layout.setHorizontalGroup(
//				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//						.addGroup(layout.createSequentialGroup().addComponent(jPanel1,
//								javax.swing.GroupLayout.PREFERRED_SIZE, 1219, javax.swing.GroupLayout.PREFERRED_SIZE)
//								.addGap(0, 0, Short.MAX_VALUE)));
//		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
//				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
//				javax.swing.GroupLayout.PREFERRED_SIZE));
//
//		pack();
//	}// </editor-fold>//GEN-END:initComponents
//
//	/**
//	 * @param args the command line arguments
//	 */
//	public static void main(String args[]) {
//		/* Set the Nimbus look and feel */
//		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
//		// (optional) ">
//		/*
//		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
//		 * look and feel. For details see
//		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//		 */
//		try {
//			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//				if ("Nimbus".equals(info.getName())) {
//					javax.swing.UIManager.setLookAndFeel(info.getClassName());
//					break;
//				}
//			}
//		} catch (ClassNotFoundException ex) {
//			java.util.logging.Logger.getLogger(FRMQuanLiThongKe.class.getName()).log(java.util.logging.Level.SEVERE,
//					null, ex);
//		} catch (InstantiationException ex) {
//			java.util.logging.Logger.getLogger(FRMQuanLiThongKe.class.getName()).log(java.util.logging.Level.SEVERE,
//					null, ex);
//		} catch (IllegalAccessException ex) {
//			java.util.logging.Logger.getLogger(FRMQuanLiThongKe.class.getName()).log(java.util.logging.Level.SEVERE,
//					null, ex);
//		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
//			java.util.logging.Logger.getLogger(FRMQuanLiThongKe.class.getName()).log(java.util.logging.Level.SEVERE,
//					null, ex);
//		}
//		// </editor-fold>
//
//		/* Create and display the form */
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				new FRMQuanLiThongKe().setVisible(true);
//			}
//		});
//	}
//
//	// Variables declaration - do not modify//GEN-BEGIN:variables
//	private javax.swing.JLabel jLabel1;
//	private javax.swing.JLabel jLabel2;
//	private javax.swing.JPanel jPanel1;
//	private javax.swing.JScrollPane jScrollPane1;
//	private javax.swing.JScrollPane jScrollPane2;
//	private javax.swing.JScrollPane jScrollPane3;
//	private javax.swing.JTextArea jTextArea1;
//	private javax.swing.JTextArea jTextArea2;
//	private javax.swing.JTextArea jTextArea3;
//	private javax.swing.JButton jbLamMoiTK;
//	private javax.swing.JButton jbThongKe;
//	private LocalDate now;
//	private int ngay;
//	private int thang;
//	private int nam;
//	private Date dNow;
//	private JDateChooser dateChooserThongKeNgayBatDau;
//	private JDateChooser dateChooserThongKeNgayKetThuc;
//	// End of variables declaration//GEN-END:variables
//}
// * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
// * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
// */
package gui;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Panel;
import java.awt.event.ActionEvent;
import java.rmi.RemoteException;
import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;

import javax.swing.*;

import com.toedter.calendar.JDateChooser;
import dao.HoaDonDao;
import impl.HoaDonImpl;

/**
 *
 * @author Asus
 */
public class FRMQuanLiThongKe extends javax.swing.JFrame {

    /**
     * Creates new form FRMQuanLiThongKe
     */
    public FRMQuanLiThongKe() {
        initComponents();
    }

    public JPanel getFRMThongKe() {
        return jPanel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbThongKe = new javax.swing.JButton();
        jbLamMoiTK = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanelTDT = new javax.swing.JPanel();
        iconTDT = new javax.swing.JLabel();
        jLabelTDT = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanelThoiGian = new javax.swing.JPanel();
        iconTG = new javax.swing.JLabel();
        jLabelTG = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        chooserNgayBatDau = new JDateChooser();
        chooserNgayBatDau.getCalendarButton().setPreferredSize(new Dimension(30, 24));
        chooserNgayBatDau.setDateFormatString("dd/MM/yyyy");
        chooserNgayBatDau.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        chooserNgayBatDau.setFont(new Font("SansSerif", Font.PLAIN, 15));
        now = LocalDate.now();
        ngay = now.getDayOfMonth();
        thang = now.getMonthValue()-1;
        nam = now.getYear()-1900;
        dHienTai = new Date(nam,thang,ngay);
        chooserNgayBatDau.setDate(dHienTai);

        chooserNgayKetThuc = new JDateChooser();
        chooserNgayKetThuc.getCalendarButton().setPreferredSize(new Dimension(30, 24));
        chooserNgayKetThuc.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        chooserNgayKetThuc.getCalendarButton().setBackground(new Color(102, 0, 153));
        chooserNgayKetThuc.setFont(new Font("SansSerif", Font.PLAIN, 15));
        chooserNgayKetThuc.setDateFormatString("dd/MM/yyyy");
        chooserNgayKetThuc.setDate(dHienTai);


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1202, 422));

        jPanel1.setPreferredSize(new java.awt.Dimension(1202, 422));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setText("Đến ngày:");


        jbThongKe.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jbThongKe.setText("Thống kê");

        jbLamMoiTK.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jbLamMoiTK.setText("Làm mới");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setText("Từ ngày:");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jPanelTDT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255)));

        iconTDT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconTDT.setText("iconTDT");

        jLabelTDT.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelTDT.setForeground(new java.awt.Color(153, 0, 204));
        jLabelTDT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTDT.setText("TỔNG DOANH THU");

        jTextField3.setBackground(new java.awt.Color(242, 242, 242));
        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("0 VNĐ");
        jTextField3.setBorder(null);
        jbThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbThongKeActionPerformed(evt);
            }
        });

        jbLamMoiTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLamMoiTKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTDTLayout = new javax.swing.GroupLayout(jPanelTDT);
        jPanelTDT.setLayout(jPanelTDTLayout);
        jPanelTDTLayout.setHorizontalGroup(
                jPanelTDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTDTLayout.createSequentialGroup()
                                .addGap(0, 159, Short.MAX_VALUE)
                                .addGroup(jPanelTDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTDTLayout.createSequentialGroup()
                                                .addGroup(jPanelTDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabelTDT)
                                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(140, 140, 140))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTDTLayout.createSequentialGroup()
                                                .addComponent(iconTDT, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(179, 179, 179))))
        );
        jPanelTDTLayout.setVerticalGroup(
                jPanelTDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTDTLayout.createSequentialGroup()
                                .addComponent(iconTDT, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelTDT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        jPanelThoiGian.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 255)));

        iconTG.setText("iconThoiGian");

        jLabelTG.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelTG.setForeground(new java.awt.Color(153, 0, 204));
        jLabelTG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTG.setText("TỔNG SỐ KHÁCH HÀNG      ");

        jTextField4.setBackground(new java.awt.Color(242, 242, 242));
        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("0 KHÁCH HÀNG");
        jTextField4.setBorder(null);

        javax.swing.GroupLayout jPanelThoiGianLayout = new javax.swing.GroupLayout(jPanelThoiGian);
        jPanelThoiGian.setLayout(jPanelThoiGianLayout);
        jPanelThoiGianLayout.setHorizontalGroup(
                jPanelThoiGianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelThoiGianLayout.createSequentialGroup()
                                .addContainerGap(137, Short.MAX_VALUE)
                                .addGroup(jPanelThoiGianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelThoiGianLayout.createSequentialGroup()
                                                .addComponent(jLabelTG)
                                                .addGap(87, 87, 87))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelThoiGianLayout.createSequentialGroup()
                                                .addComponent(iconTG, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(196, 196, 196))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelThoiGianLayout.createSequentialGroup()
                                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(171, 171, 171))))
        );
        jPanelThoiGianLayout.setVerticalGroup(
                jPanelThoiGianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelThoiGianLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(iconTG, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTG, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(chooserNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                                                .addComponent(chooserNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jbThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jbLamMoiTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addComponent(jPanelTDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(351, 351, 351))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanelTDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(chooserNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(chooserNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jbThongKe)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jbLamMoiTK)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jPanelThoiGian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbLamMoiTKActionPerformed(ActionEvent evt) {
// TODO add your handling code here:
        jTextField3.setText("0 VNĐ");
        jTextField4.setText("0 KHÁCH HÀNG");
        chooserNgayBatDau.setDate(dHienTai);
        chooserNgayKetThuc.setDate(dHienTai);
    }

    private void jbThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbThongKeActionPerformed
        // TODO add your handling code here:
        try {
            thongKe();
        } catch (RemoteException ex) {
            throw new RuntimeException(ex);
        }
    }//GEN-LAST:event_jbThongKeActionPerformed

    private void thongKe() throws RemoteException{
        java.util.Date ngayBatDau = chooserNgayBatDau.getDate();
        java.util.Date ngayKetThuc = chooserNgayKetThuc.getDate();
        //Thống kê doanh thu
        hoaDonDao = new HoaDonImpl();
        double doanhThu = hoaDonDao.tongDoanhThu(ngayBatDau, ngayKetThuc);
        jTextField3.setText(doanhThu + " VNĐ");

        long soKhachHang = hoaDonDao.demSoKH(ngayBatDau, ngayKetThuc);
        jTextField4.setText(soKhachHang + " KHÁCH HÀNG");

        //Thống kê thời gian hoạt động


    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMQuanLiThongKe.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMQuanLiThongKe.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMQuanLiThongKe.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMQuanLiThongKe.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMQuanLiThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconTDT;
    private javax.swing.JLabel iconTG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTDT;
    private javax.swing.JLabel jLabelTG;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelTDT;
    private javax.swing.JPanel jPanelThoiGian;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton jbLamMoiTK;
    private javax.swing.JButton jbThongKe;
    private JDateChooser chooserNgayBatDau;
    private JDateChooser chooserNgayKetThuc;
    private LocalDate now;
    private int ngay;
    private int thang;
    private int nam;
    private Date dHienTai;
    private HoaDonDao hoaDonDao;
    // End of variables declaration//GEN-END:variables
}
