package gui;
public class FRMThanhToan {
}
//
///*
// * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
// * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
// */
//package gui;
//
//
//import java.awt.HeadlessException;
//import java.awt.Panel;
//import java.awt.Toolkit;
//import java.awt.event.ActionEvent;
//import java.awt.event.ActionListener;
//import java.awt.event.WindowEvent;
//import java.rmi.RemoteException;
//import java.sql.Date;
//import java.sql.SQLException;
//import java.sql.Time;
//import java.text.DecimalFormat;
//import java.util.ArrayList;
//
//import javax.swing.JOptionPane;
//import javax.swing.JPanel;
//import javax.swing.JTable;
//import javax.swing.table.DefaultTableModel;
//
//import dao.*;
//import entity.*;
//import impl.*;
//
//
///**
// *
// * @author Mai
// */
//public class FRMThanhToan extends javax.swing.JFrame implements ActionListener {
//
//    private FRMDanhSachHoaDon hoaDon;
//    private FRMQuanLi quanLi;
//    private LoaiMhDao daoLoaiMH;
//    private MacHangDao daoMH;
//
//    private KhachHangDao daoKhachHang;
//    private CTDDPDao daoCTDDP;
//    private NhanVienDao daoNV;
//
//
//
//    /**
//     * Creates new form FRMThanhToan
//     */
//    public FRMThanhToan(String maTK) throws RemoteException {
//        initComponents();
//        this.maTK = maTK;
//    }
//
//    public JPanel getFRMThanhToan() {
//
//        return jPanel1;
//
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() throws RemoteException {
//        // kết nối csdl
////        try {
////            ConnectDB.getinstance().connect();
////        } catch (SQLException e) {
////            e.printStackTrace();
////        }
//        daoLoaiMH = new LoaiMhImpl();
//        daoMH = new MatHangImpl();
//        daoCTDDP = new CTDDPImpl();
//        regex = new Regex();
//        daoDDP = new DDPDao();
//        daoKhachHang = new KhachHangImpl();
//        daoPhong = new PhongDao();
//        daoNV = new NhanVienImpl();
//        daoMa = new DAOSinhMaTuDong();
////		Định dạng tiền:
//        dfTable = new DecimalFormat("###,###");
////		df = new DecimalFormat("###,### VNĐ");
//
//
//        jLabel7 = new javax.swing.JLabel();
//        jPanel1 = new javax.swing.JPanel();
//        jLabel1 = new javax.swing.JLabel();
//        jScrollPane1 = new javax.swing.JScrollPane();
//        jLabel2 = new javax.swing.JLabel();
//        jPanel3 = new javax.swing.JPanel();
//        jLabel3 = new javax.swing.JLabel();
//        jLabel4 = new javax.swing.JLabel();
//        jLabel5 = new javax.swing.JLabel();
//        jComLoaiMH = new javax.swing.JComboBox<>();
//        jTSoLuong = new javax.swing.JTextField();
//        jComboBoxTenMH = new javax.swing.JComboBox<>();
//        jLabel6 = new javax.swing.JLabel();
//        jPanel4 = new javax.swing.JPanel();
//        jLabel8 = new javax.swing.JLabel();
//        jComGio = new javax.swing.JComboBox<>();
//        jLabel9 = new javax.swing.JLabel();
//        jComPhut = new javax.swing.JComboBox<>();
//        jLabel10 = new javax.swing.JLabel();
//        jTMaNV = new javax.swing.JTextField();
//        jLabel11 = new javax.swing.JLabel();
//        jComPhuThu = new javax.swing.JComboBox<>();
//        jButton2 = new javax.swing.JButton();
//        jLabel12 = new javax.swing.JLabel();
//        jTextFieldTimHD = new javax.swing.JTextField();
//        jbTimHD = new javax.swing.JButton();
//        jPanel2 = new javax.swing.JPanel();
//        jLabel13 = new javax.swing.JLabel();
//        jLabel14 = new javax.swing.JLabel();
//        jLabel15 = new javax.swing.JLabel();
//        jLabel16 = new javax.swing.JLabel();
//        jTPhutVao = new javax.swing.JTextField();
//        jTGioVao = new javax.swing.JTextField();
//        jTTenKH = new javax.swing.JTextField();
//        jTextField1 = new javax.swing.JTextField();
//        jLabel21 = new javax.swing.JLabel();
//        txtMaKH = new javax.swing.JTextField();
//        btnThemDDP = new javax.swing.JButton();
//        btnLamMoiDDP = new javax.swing.JButton();
//        btnXoaDDP = new javax.swing.JButton();
//        jScrollPane2 = new javax.swing.JScrollPane();
//        jTable1 = new javax.swing.JTable();
//        jPanel5 = new javax.swing.JPanel();
//        jButton1 = new javax.swing.JButton();
//        jLabel17 = new javax.swing.JLabel();
//        jLabel18 = new javax.swing.JLabel();
//        jLabel19 = new javax.swing.JLabel();
//        jTTienPhuThu = new javax.swing.JTextField();
//        jTThoiGian = new javax.swing.JTextField();
//        jTThanhTien = new javax.swing.JTextField();
//        btnLamMoiDDP1 = new javax.swing.JButton();
//        jLabel20 = new javax.swing.JLabel();
//        JTGiaPhong = new javax.swing.JTextField();
//        jButtonDanhSachHoaDon = new javax.swing.JButton();
//
//        jLabel7.setText("jLabel7");
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jPanel1.setPreferredSize(new java.awt.Dimension(1202, 422));
//
//        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
//        jLabel1.setText("Phòng hát:");
//
//        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
//        jLabel2.setText("Dịch vụ:");
//
//        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
//        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
//
//        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//        jLabel3.setText("Loại mặt hàng:");
//
//        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//        jLabel4.setText("Tên mặt hàng:");
//
//        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//        jLabel5.setText("Số lượng:");
//
//        jComLoaiMH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bia", "Nước ngọt", "Món ăn", " " }));
//
//        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
//        jPanel3.setLayout(jPanel3Layout);
//        jPanel3Layout.setHorizontalGroup(
//                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel3Layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(jPanel3Layout.createSequentialGroup()
//                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addComponent(jTSoLuong))
//                                        .addGroup(jPanel3Layout.createSequentialGroup()
//                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addComponent(jComLoaiMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addGap(0, 0, Short.MAX_VALUE))
//                                        .addGroup(jPanel3Layout.createSequentialGroup()
//                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addComponent(jComboBoxTenMH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
//                                .addGap(48, 48, 48))
//        );
//        jPanel3Layout.setVerticalGroup(
//                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel3Layout.createSequentialGroup()
//                                .addGap(14, 14, 14)
//                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jLabel3)
//                                        .addComponent(jComLoaiMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(jPanel3Layout.createSequentialGroup()
//                                                .addGap(23, 23, 23)
//                                                .addComponent(jLabel4))
//                                        .addGroup(jPanel3Layout.createSequentialGroup()
//                                                .addGap(18, 18, 18)
//                                                .addComponent(jComboBoxTenMH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jTSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jLabel5))
//                                .addContainerGap(14, Short.MAX_VALUE))
//        );
//
//        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
//        jLabel6.setText("Thông tin hoá đơn:");
//
//        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
//        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
//
//        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//        jLabel8.setText("Giờ ra:");
//
//        jComGio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "0" }));
//
//        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
//        jLabel9.setText(":");
//
//        jComPhut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "56", "57", "58", "59", "0" }));
//
//        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//        jLabel10.setText("Nhân viên:");
//
//        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//        jLabel11.setText("Phụ thu:");
//
//        jComPhuThu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày thường", "Đêm", "Ngày lễ" }));
//
//        jButton2.setIcon(new javax.swing.ImageIcon("D:\\PhatTrienUngDung\\baiTapLonCKPTUD\\baiTapLonCKPTUD\\iCon\\bill.png")); // NOI18N
//
//        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
//        jPanel4.setLayout(jPanel4Layout);
//        jPanel4Layout.setHorizontalGroup(
//                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel4Layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(jPanel4Layout.createSequentialGroup()
//                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                        .addGroup(jPanel4Layout.createSequentialGroup()
//                                                                .addComponent(jComGio, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                                .addGap(18, 18, 18)
//                                                                .addComponent(jLabel9)
//                                                                .addGap(18, 18, 18)
//                                                                .addComponent(jComPhut, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                                        .addComponent(jTMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                        .addGroup(jPanel4Layout.createSequentialGroup()
//                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                                .addComponent(jComPhuThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//        jPanel4Layout.setVerticalGroup(
//                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel4Layout.createSequentialGroup()
//                                .addGap(12, 12, 12)
//                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                                .addComponent(jComGio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addComponent(jComPhut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jLabel10)
//                                        .addComponent(jTMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(jPanel4Layout.createSequentialGroup()
//                                                .addGap(13, 13, 13)
//                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                                        .addComponent(jLabel11)
//                                                        .addComponent(jComPhuThu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                        .addGroup(jPanel4Layout.createSequentialGroup()
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                .addContainerGap(22, Short.MAX_VALUE))
//        );
//
//        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
//        jLabel12.setText("Tìm kiếm:");
//
//        jTextFieldTimHD.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextFieldTimHDActionPerformed(evt);
//            }
//        });
//
//        jbTimHD.setIcon(new javax.swing.ImageIcon("D:\\PhatTrienUngDung\\baiTapLonCKPTUD\\baiTapLonCKPTUD\\iCon\\search.png")); // NOI18N
//
//        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
//
//        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//        jLabel13.setText("Phòng:");
//
//        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//        jLabel14.setText("Tên Khách hàng:");
//
//        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//        jLabel15.setText("Giờ ra:");
//
//        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//        jLabel16.setText(":");
//
//        jLabel21.setText("Mã KH");
//
//        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
//        jPanel2.setLayout(jPanel2Layout);
//        jPanel2Layout.setHorizontalGroup(
//                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
//                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
//                                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                                .addGap(73, 73, 73)))
//                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
//                                                .addComponent(jTTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addGap(27, 27, 27))
//                                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addGap(119, 119, 119)))
//                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addComponent(txtMaKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                                .addComponent(jTGioVao, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addComponent(jTPhutVao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                .addContainerGap())
//        );
//        jPanel2Layout.setVerticalGroup(
//                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                        .addComponent(jLabel13))
//                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                                        .addComponent(jTGioVao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                        .addComponent(jLabel16)
//                                                        .addComponent(jTPhutVao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                                .addGap(0, 0, Short.MAX_VALUE)
//                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                                        .addComponent(jLabel14)
//                                                        .addComponent(jTTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                        .addComponent(jLabel21)))
//                                        .addComponent(txtMaKH))
//                                .addContainerGap())
//        );
//
//        btnThemDDP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
//        btnThemDDP.setText("Thêm");
//        btnThemDDP.setPreferredSize(new java.awt.Dimension(121, 39));
//
//        btnLamMoiDDP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//        btnLamMoiDDP.setText("Làm Mới");
//        btnLamMoiDDP.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnLamMoiDDPActionPerformed(evt);
//            }
//        });
//
//        btnXoaDDP.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
//        btnXoaDDP.setText("Xóa");
//        btnXoaDDP.setPreferredSize(new java.awt.Dimension(121, 39));
//
////        jTable1.setModel(new javax.swing.table.DefaultTableModel(
////            new Object [][] {
////                {null, null, null, null, null},
////                {null, null, null, null, null},
////                {null, null, null, null, null},
////                {null, null, null, null, null},
////                {null, null, null, null, null},
////                {null, null, null, null, null},
////                {null, null, null, null, null},
////                {null, null, null, null, null},
////                {null, null, null, null, null},
////                {null, null, null, null, null}
////            },
////            new String [] {
////                "Loại mặt hàng", "Tên mặt hàng", "Số lượng", "Giá bán", "Thành tiền"
////            }
////        ));
//        String col []={
//                "Loại mặt hàng", "Tên mặt hàng", "Số lượng", "Giá bán", "Thành tiền"
//        };
//        modelThanhToan = new DefaultTableModel(col,0);
//        jTable1 = new JTable(modelThanhToan);
//
//        jScrollPane2.setViewportView(jTable1);
//
//        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
//
//        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
//        jButton1.setIcon(new javax.swing.ImageIcon("D:\\PhatTrienUngDung\\baiTapLonCKPTUD\\baiTapLonCKPTUD\\iCon\\pay.png")); // NOI18N
//        jButton1.setText("Thanh toán");
//        jButton1.setPreferredSize(new java.awt.Dimension(121, 39));
//
//        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
//        jLabel17.setText("Tiền nhận:");
//
//        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
//        jLabel18.setText("Thời gian:");
//
//        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
//        jLabel19.setText("Thành tiền:");
//
//        btnLamMoiDDP1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//        btnLamMoiDDP1.setIcon(new javax.swing.ImageIcon("D:\\PhatTrienUngDung\\baiTapLonCKPTUD\\baiTapLonCKPTUD\\iCon\\refresh.png")); // NOI18N
//        btnLamMoiDDP1.setText("Làm Mới");
//        btnLamMoiDDP1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnLamMoiDDP1ActionPerformed(evt);
//            }
//        });
//
//        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
//        jLabel20.setText("Giá phòng:");
//
//        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
//        jPanel5.setLayout(jPanel5Layout);
//        jPanel5Layout.setHorizontalGroup(
//                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel5Layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addComponent(jLabel17)
//                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(11, 11, 11)
//                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                        .addComponent(jTThoiGian, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
//                                        .addComponent(jTTienPhuThu))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addComponent(jLabel20)
//                                        .addComponent(jLabel19))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                        .addComponent(jTThanhTien, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
//                                        .addComponent(JTGiaPhong))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(btnLamMoiDDP1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//        jPanel5Layout.setVerticalGroup(
//                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel5Layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(jPanel5Layout.createSequentialGroup()
//                                                .addGap(68, 68, 68)
//                                                .addComponent(jLabel18))
//                                        .addGroup(jPanel5Layout.createSequentialGroup()
//                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                                                .addComponent(jTTienPhuThu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                                .addComponent(jLabel17)
//                                                                .addComponent(jLabel20)
//                                                                .addComponent(JTGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                                        .addComponent(jTThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                        .addComponent(jTThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                        .addComponent(btnLamMoiDDP1))))
//                                .addContainerGap(8, Short.MAX_VALUE))
//        );
//
//        jButtonDanhSachHoaDon.setIcon(new javax.swing.ImageIcon("D:\\PhatTrienUngDung\\baiTapLonCKPTUD\\baiTapLonCKPTUD\\iCon\\bill (1).png")); // NOI18N
//        jButtonDanhSachHoaDon.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButtonDanhSachHoaDonActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//        jPanel1.setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel1Layout.createSequentialGroup()
//                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(jPanel1Layout.createSequentialGroup()
//                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                        .addGroup(jPanel1Layout.createSequentialGroup()
//                                                                .addGap(26, 26, 26)
//                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                                        .addComponent(btnXoaDDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                                        .addComponent(btnLamMoiDDP)
//                                                                        .addComponent(btnThemDDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
//                                                .addGap(34, 34, 34))
//                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
//                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                        .addGroup(jPanel1Layout.createSequentialGroup()
//                                                .addGap(26, 26, 26)
//                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addComponent(jTextFieldTimHD, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addGap(39, 39, 39)
//                                                .addComponent(jbTimHD, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addComponent(jButtonDanhSachHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                        .addComponent(jScrollPane2)
//                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//        jPanel1Layout.setVerticalGroup(
//                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel1Layout.createSequentialGroup()
//                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
//                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
//                                                                .addGap(36, 36, 36)
//                                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                                .addGap(0, 0, Short.MAX_VALUE))
//                                                        .addGroup(jPanel1Layout.createSequentialGroup()
//                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                                .addComponent(btnThemDDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                                .addComponent(btnXoaDDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                                .addComponent(btnLamMoiDDP)
//                                                                .addGap(12, 12, 12)))
//                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                                                        .addContainerGap()
//                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
//                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                                                        .addComponent(jTextFieldTimHD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                                                .addComponent(jbTimHD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                                                .addComponent(jButtonDanhSachHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                                                        .addGap(7, 7, 7)
//                                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                        .addGap(7, 7, 7)
//                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                        .addComponent(jLabel1)
//                                        .addComponent(jLabel2))
//                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1190, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(0, 0, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(0, 8, Short.MAX_VALUE))
//        );
//
//        pack();
//        // add sự kiện
//        btnThemDDP.addActionListener(this);
//        jbTimHD.addActionListener(this);
//        btnXoaDDP.addActionListener(this);
//        pack();
/////		Load tên loại mặt hàng
//        ArrayList<LoaiMH> lsLoaiMH = daoLoaiMH.getAllLoaiMatHang();
//        for(LoaiMH lmh : lsLoaiMH) {
//            jComLoaiMH.addItem(lmh.getTenLoaiMatHang());
//        }
//
////		 Load ten mat hang mac dinh :
//        String tenMH = (String) jComLoaiMH.getSelectedItem();
//        String maLoaiMatHang = String.valueOf(daoLoaiMH.getLMHTheoTen(tenMH).getMaLoaiMatHang());
//        ArrayList<MatHang> lsMH = daoMH.getMHTheoLoai(maLoaiMatHang);
//        jComboBoxTenMH.removeAllItems();
//        for(MatHang mh : lsMH) {
//            jComboBoxTenMH.addItem(mh.getTenMatHang());
//        }
//
//        jTMaNV.setText(daoNV.getNVTheoTK(maTK).getTenNhanVien());
//
//    }// </editor-fold>//GEN-END:initComponents
//
//
//    private void jTextFieldTimHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTimHDActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_jTextFieldTimHDActionPerformed
//
//    private void btnLamMoiDDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiDDPActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_btnLamMoiDDPActionPerformed
//
//    private void btnLamMoiDDP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiDDP1ActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_btnLamMoiDDP1ActionPerformed
//
//
//    private void jButtonDanhSachHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDanhSachHoaDonActionPerformed
//        // TODO add your handling code here:
//        hoaDon = new FRMDanhSachHoaDon();
//        hoaDon.setVisible(true);
//        this.setVisible(false);
//    }//GEN-LAST:event_jButtonDanhSachHoaDonActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FRMThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FRMThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FRMThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FRMThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//
//
//
//            public void run() {
//                try {
//                    new FRMThanhToan(maTK).setVisible(true);
//                } catch (RemoteException e) {
//                    throw new RuntimeException(e);
//                }
//            }
//        });
//    }
//    /////////////////////
//    //load thông tin mặt hàng của ddp lên talbe
//    public void loadTable(DonDatPhong ddp) throws RemoteException {
//        clearTable();
//        ArrayList<ChiTietDDP> lsCTDDP = daoCTDDP.getCTDDPTheoMaDDP(ddp.getMaDDP());
//
//        for(ChiTietDDP ctddp : lsCTDDP) {
//            MatHang mh = daoMH.getMHTheoMa(ctddp.getMatHang().getMaMatHang());
//            LoaiMH loaiMH = daoLoaiMH.getLMHTheoMa(mh.getLoaiMatHang().getMaLoaiMatHang());
//            double tongTien = mh.getGiaMatHang() * ctddp.getSoLuongMH();
//            modelThanhToan.addRow(new Object[] {
//                    mh.getTenMatHang(),loaiMH.getTenLoaiMatHang(),ctddp.getSoLuongMH(),dfTable.format(Math.round( mh.getGiaMatHang())),dfTable.format(Math.round(tongTien))
//            });
//        }
//    }
//    private void clearTable() {
//        while(jTable1.getRowCount()>0) {
//            modelThanhToan.removeRow(0);
//
//        }
//    }
//    // load info
//    public void loadInfo(Phong p) throws RemoteException {
////   		jTMaNV.setText(p.getMaPhong());
//        jTextField1.setText(p.getMaPhong()); // mã phòng
//        DonDatPhong ddp = daoDDP.getDDPTheoMaPhong(p.getMaPhong());
//
//        KhachHang kh = daoKhachHang.getKHTheoMa(ddp.getKhachHang().getMaKhangHang());
//        Time gioDen = ddp.getGioDen();
//        txtMaKH.setText(kh.getMaKhangHang());
//        jTTenKH.setText(" - "+kh.getTenKH());
//        jTGioVao.setText(""+gioDen.getHours());
//        jTPhutVao.setText(""+gioDen.getMinutes());
//
//        loadTable(ddp);
//    }
//    // tim kiếm phòng đang hd -> thanh toán
//    public void timKiem() {
//        try {
//            if(regex.regexTimKiemMaPhong(jTextFieldTimHD)) {
//                Phong p1 = daoPhong.getPhongDangHoatDongTheoMaP(jTextFieldTimHD.getText().toString());
//                if(p1!=null)
//                    loadInfo(p1);
//                else
//                    JOptionPane.showMessageDialog(this, "Không tìm thấy phòng đang hoạt động nào như yêu cầu!");
//            }
//        } catch (HeadlessException | RemoteException e) {
//            // TODO Auto-generated catch block
//            e.printStackTrace();
//        }
//    }
//    /**
//     * Tìm số lượng của 1 mặt hàng. Nếu mặt hàng có trong bảng mặt hàng thì trả về số lượng mặt hàng trong bảng đó
//     * @return số lượng mặt hàng
//     */
//    public int getSoLuongMH() {
//        int soLuong = 0;
//        if(timRow() != -1) {
//            soLuong = Integer.parseInt(modelThanhToan.getValueAt(timRow(), 2).toString()) + Integer.parseInt(jTSoLuong.getText());
//            return soLuong;
//        }
//        else return Integer.parseInt(jTSoLuong.getText());
//    }
//    /**
//     * Tìm 1 hàng trong bảng mặt hàng, nếu tìm thấy sẽ trả về vị trí trong bảng của mặt hàng đó.
//     * @return vị trí hàng
//     */
//    public int timRow() {
//
//        for(int i =0; i< jTable1.getRowCount(); i++) {
//            if(modelThanhToan.getValueAt(i, 0).toString().equalsIgnoreCase(jComboBoxTenMH.getSelectedItem().toString())&& modelThanhToan.getValueAt(i, 1).toString().equalsIgnoreCase(jComLoaiMH.getSelectedItem().toString()))
//                return i;
//        }
//        return -1;
//    }
//    //	  Tìm mặt hàng trong bảng, nếu tìm thấy thì sửa số lượng mặt hàng ở bảng theo CTHD
////	  @param ctddp
////	  @param matHang
////	  @return boolean
////
//    public boolean kiemTraMatHangTrongBang(ChiTietDDP ctddp, MatHang mh) {
//        if(timRow() != -1) {
//            daoCTDDP.suaSoluongMH(ctddp.getDonDatPhong().getMaDDP(), ctddp.getMatHang().getMaMatHang(), getSoLuongMH());
//            modelThanhToan.setValueAt(getSoLuongMH(),timRow(), 2);
//            double giaMoi = mh.getGiaMatHang()* Integer.parseInt(modelThanhToan.getValueAt(timRow(), 2).toString());
//            modelThanhToan.setValueAt(dfTable.format(giaMoi), timRow(), 4);
//
//
//            return false;
//        }
//        return true;
//
//    }
//    /**
//     * Thêm một mặt hàng vào bảng.
//     * Nếu thông tin hợp lệ sẽ tạo đối tượng chi tiết hóa đơn và kiểm tra nút giảm số lượng có được chọn không
//     * Nếu được chọn sẽ thực hiện gọi phương thức giảm số lượng.
//     * Nếu không được chọn sẽ kiểm tra trong bảng có mặt hàng chưa, nếu có thì cập nhật số lượng, không thì sẽ được thêm mới
//     */
//
//    public void themMHVaoCTDDP() {
//        if(jTextField1.getText() != "") {
//            if(regex.regexSoLuong(jTSoLuong)) {
//                DonDatPhong ddp = daoDDP.getDDPTheoMaPhong(jTextField1.getText());
//
//                String tenMH = jComboBoxTenMH.getSelectedItem().toString();
//                String loaiMH = jComLoaiMH.getSelectedItem().toString();
//                MatHang mh = daoMH.getMHTheoTenMHVaLoaiMH(tenMH, loaiMH);
//                int soLuongMH = Integer.parseInt(jTSoLuong.getText());
//                int soLuongTon = mh.getSoLuongMatHang();
//                ChiTietDDP ctddp = new ChiTietDDP(ddp, soLuongMH, mh);
//
////						if(rdbtnGiamSL.isSelected()) {
////							kiemTraGiamSL(ctddp);
////							mh.setSoLuongMatHang(soLuongTon+soLuongMH);
////							daoMatHang.updateMH(mh);
////
////						}
//                if(soLuongMH <= soLuongTon) {
//                    if(kiemTraMatHangTrongBang(ctddp,mh)) {
//                        daoCTDDP.themCTDDP(ctddp);
//                        double tongTien = mh.getGiaMatHang() * ctddp.getSoLuongMH();
//                        modelThanhToan.addRow(new Object[] {
//                                tenMH,loaiMH,ctddp.getSoLuongMH(),dfTable.format(Math.round( mh.getGiaMatHang())),dfTable.format(Math.round(tongTien))
//                        });
//                    }
//
//                    mh.setSoLuongMatHang(soLuongTon-soLuongMH);
//                    daoMH.updateMH(mh);
//                }
//                else JOptionPane.showMessageDialog(this, "Số lượng mặt hàng tồn không đủ cung cấp!\nVui lòng nhập lại số lượng.");
//
//            }
//        }
//        else JOptionPane.showMessageDialog(this, "Vui lòng chọn phòng sau đó nhập số lượng trước khi thêm mặt hàng!");
//    }
//    // reset thanh toán
//    public void resetThanhToan() {
//
//    }
//
//
////	  Xóa 1 mặt hàng hd sau đó các mục sẽ được làm mới.
////	  Phòng phải được chọn.
////	  Trước khi xóa phải chọn một mặt hàng cần xóa
//
//    public void xoaCTDDP() {
//        // mã phòng
//        if(!jTextField1.getText().equalsIgnoreCase("")) {
//            if(timRow() != -1) {
//                DonDatPhong ddp = daoDDP.getDDPTheoMaPhong(jTextField1.getText());
//
//                String tenMH = jComboBoxTenMH.getSelectedItem().toString();
//                String loaiMH = jComLoaiMH.getSelectedItem().toString();
//                MatHang mh = daoMH.getMHTheoTenMHVaLoaiMH(tenMH, loaiMH);
//                daoCTDDP.xoaCTDDP(ddp.getMaDDP(),mh.getMaMatHang());
//
//                int soLuongMH = Integer.parseInt(modelThanhToan.getValueAt(timRow(), 2).toString());
//                int soLuongTon = mh.getSoLuongMatHang();
//
//                mh.setSoLuongMatHang(soLuongTon+soLuongMH);
//                daoMH.updateMH(mh);
//                loadTable(ddp);
//                resetDichVu();
//            }
//            else JOptionPane.showMessageDialog(this, "Vui lòng chọn mặt hàng cần xóa");
//        }
//        else JOptionPane.showMessageDialog(this, "Vui lòng chọn phòng và chọn mặt hàng cần xóa");
//
//    }
//    // làm mới các mục của dịch vụ
//    public void resetDichVu() {
//        jComboBoxTenMH.setSelectedIndex(0);
//        jComLoaiMH.setSelectedIndex(0);
//        jTSoLuong.setText("");
//
//
//    }
//    ///
//    /**
//     * Giúp thêm một hóa đơn mới.
//     * Sẽ kiểm tra thông tin đầy đủ trước khi thực hiện lưu thông tin lên database.
//     * Sau khi thêm hóa đơn thành công sẽ cập nhật lại trạng thái phòng, điểm tích lũy nếu là thành viên
//     */
//    //đang lỗi
//    // thêm field mã khách
////	public void themHD() {
////		int optThanhToan = JOptionPane.showConfirmDialog(this, "Bạn có chắn chắn muốn thanh toán không?", "Thông báo", JOptionPane.YES_NO_OPTION );
////
////		if(optThanhToan == JOptionPane.YES_OPTION) {
////			// mã phòng
////			if(jTextField1.getText().toString() !="") {
////				if(!jTThanhTien.getText().equalsIgnoreCase("")) {
////					String maHD = daoMa.getMaHD();
////					Phong p = daoPhong.getPhongTheoMa(jTextField1.getText());
////					KhachHang kh = daoKhachHang.getKHTheoMa(lblMaKH.getText());
////					NhanVien nv = daoNhanVien.getNVTheoMa(sHeaderMaNV);
////					Date ngayLap = dNgayHienTai;
////
////					int gioVao = Integer.parseInt(lblGioVao.getText()),
////						phutVao = Integer.parseInt(lblPhutVao.getText());
////					int gioRa = Integer.parseInt(cbbGioRa.getSelectedItem().toString()),
////							phutRa = Integer.parseInt(cbbPhutRa.getSelectedItem().toString());
////					String phuThu = cbbPhuThu.getSelectedItem().toString();
////					String trangThaiHD = "Đã thanh toán";
////					double giamGiaThanhToan = this.giamGia;
////
////
////					@SuppressWarnings("deprecation")
////					HoaDon hd = new HoaDon(maHD, ngayLap, new Time(gioVao, phutVao, 0), new Time(gioRa, phutRa, 0), phuThu, trangThaiHD,giamGiaThanhToan, nv, kh, p);
////					daoHD.themHoaDon(hd);
////					themCTHD(hd);
////
////					daoKhachHang.suaThongTinKhachHang(capNhatKHThanhToan(kh));
////					daoPhong.capnhatTrangThaiPhong(p.getMaPhong(), "Trống");
////					DonDatPhong ddp = daoDDP.getDDPTheoMaPhong(p.getMaPhong());
////					try {
////						daoDDP.capNhatTrangThaiDDP(ddp.getMaDDP());
////					} catch (SQLException e) {
////						e.printStackTrace();
////					}
////					JOptionPane.showMessageDialog(this, "Thanh toán thành công");
////					resetAll();
////				}
////				else JOptionPane.showMessageDialog(this, "Vui lòng chọn thời gian hợp lệ trước khi thanh toán!");
////			}
////			else JOptionPane.showMessageDialog(this, "Vui lòng chọn phòng trước khi thanh toán!");
////		}
////
////	}
////
////
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JTextField JTGiaPhong;
//    private javax.swing.JButton btnLamMoiDDP;
//    private javax.swing.JButton btnLamMoiDDP1;
//    private javax.swing.JButton btnThemDDP;
//    private javax.swing.JButton btnXoaDDP;
//    private javax.swing.JButton jButton1;
//    private javax.swing.JButton jButton2;
//    private javax.swing.JButton jButtonDanhSachHoaDon;
//    private javax.swing.JComboBox<String> jComGio;
//    private javax.swing.JComboBox<String> jComLoaiMH;
//    private javax.swing.JComboBox<String> jComPhuThu;
//    private javax.swing.JComboBox<String> jComPhut;
//    private javax.swing.JComboBox<String> jComboBoxTenMH;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel10;
//    private javax.swing.JLabel jLabel11;
//    private javax.swing.JLabel jLabel12;
//    private javax.swing.JLabel jLabel13;
//    private javax.swing.JLabel jLabel14;
//    private javax.swing.JLabel jLabel15;
//    private javax.swing.JLabel jLabel16;
//    private javax.swing.JLabel jLabel17;
//    private javax.swing.JLabel jLabel18;
//    private javax.swing.JLabel jLabel19;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel20;
//    private javax.swing.JLabel jLabel21;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JLabel jLabel4;
//    private javax.swing.JLabel jLabel5;
//    private javax.swing.JLabel jLabel6;
//    private javax.swing.JLabel jLabel7;
//    private javax.swing.JLabel jLabel8;
//    private javax.swing.JLabel jLabel9;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JPanel jPanel2;
//    private javax.swing.JPanel jPanel3;
//    private javax.swing.JPanel jPanel4;
//    private javax.swing.JPanel jPanel5;
//    private javax.swing.JScrollPane jScrollPane1;
//    private javax.swing.JScrollPane jScrollPane2;
//    private javax.swing.JTextField jTGioVao;
//    private javax.swing.JTextField jTMaNV;
//    private javax.swing.JTextField jTPhutVao;
//    private javax.swing.JTextField jTSoLuong;
//    private javax.swing.JTextField jTTenKH;
//    private javax.swing.JTextField jTThanhTien;
//    private javax.swing.JTextField jTThoiGian;
//    private javax.swing.JTextField jTTienPhuThu;
//    private javax.swing.JTable jTable1;
//    private javax.swing.JTextField jTextField1;
//    private javax.swing.JTextField jTextFieldTimHD;
//    private javax.swing.JButton jbTimHD;
//    private javax.swing.JTextField txtMaKH;
//    // End of variables declaration//GEN-END:variables
//    private DecimalFormat dfTable;
//    //// khai bao cac dao
//    private DAOCTDDP daoCTDDP;
//    private Regex regex;
//    private DAOPhong daoPhong;
//    private DaoDatPhong daoDDP;
//    private DAOKhachHang daoKhachHang;
//    private DAONhanVien daoNV;
//    private DAOSinhMaTuDong daoMa;
//    private DAONhanVien daoNhanVien;
//    //
//    private static String maTK;
//    private DefaultTableModel modelThanhToan;
//
//
//
//    @Override
//    public void actionPerformed(ActionEvent e) {
//        // TODO Auto-generated method stub
//        Object o = e.getSource();
//        if(o.equals(jbTimHD)) {
//            timKiem();
//        }
//        if(o.equals(btnThemDDP)) {
//            themMHVaoCTDDP();
//        }
//        if(o.equals(btnXoaDDP)) {
//            xoaCTDDP();
//        }
//
//    }
//}
